# Generated by Django 3.2.6 on 2021-08-23 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код направления')),
                ('director', models.CharField(max_length=100, verbose_name='Директор')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('Дисциплина', 'Дисциплина'), ('Практика', 'Практика'), ('Факультатив', 'Факультатив'), ('Курсовая работа', 'Курсовая работа')], max_length=20, null=True, verbose_name='Типы')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_units', models.SmallIntegerField()),
                ('hours', models.SmallIntegerField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.disciplines')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название группы')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.directions', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=20, verbose_name='Представление')),
                ('mark', models.SmallIntegerField(verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('last_name_dp', models.CharField(max_length=51, verbose_name='Фамилия(дательный падеж)')),
                ('first_name_dp', models.CharField(max_length=51, verbose_name='Имя(дательный падеж)')),
                ('middle_name_dp', models.CharField(max_length=51, verbose_name='Отчество(дательный падеж)')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('м', 'мужской'), ('ж', 'женский')], max_length=10, verbose_name='Пол')),
                ('snils', models.CharField(max_length=14, verbose_name='СНИЛС')),
                ('form_of_education', models.CharField(choices=[('О', 'Очная'), ('З', 'Заочная'), ('ОЗ', 'Очно-заочная')], max_length=20, verbose_name='Форма обучения')),
                ('qualification', models.CharField(max_length=40, verbose_name='Квалификация')),
                ('seria_and_numder', models.CharField(max_length=40, verbose_name='Серия и номер')),
                ('year_education', models.CharField(max_length=4, verbose_name='Год выдачи предыдущего документа об образовании')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.countries', verbose_name='Город')),
                ('education_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.documents', verbose_name='Документ об образовании')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='PracticesGroupMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.marks', verbose_name='Оценка')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.disciplinesgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.students')),
            ],
        ),
        migrations.CreateModel(
            name='PracticesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_units', models.SmallIntegerField()),
                ('hours', models.SmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.groups')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.disciplines')),
            ],
        ),
        migrations.CreateModel(
            name='FacultativesGroupMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.disciplinesgroup')),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.marks', verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.students')),
            ],
        ),
        migrations.CreateModel(
            name='FacultativesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_units', models.SmallIntegerField()),
                ('hours', models.SmallIntegerField()),
                ('facultative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.disciplines')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.groups')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinesGroupMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.disciplinesgroup', verbose_name='Дисциплина')),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.marks', verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.students', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Оценка по дисциплине',
                'verbose_name_plural': 'Оценки по дисциплинам',
            },
        ),
        migrations.AddField(
            model_name='disciplinesgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.groups'),
        ),
        migrations.CreateModel(
            name='CourseworkGroupMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField()),
                ('courseworks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.disciplinesgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.students')),
            ],
        ),
        migrations.CreateModel(
            name='CourseworkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField()),
                ('coursework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.disciplines')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.groups')),
            ],
        ),
    ]
