# Generated by Django 3.2.6 on 2021-08-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name_dp',
            field=models.CharField(max_length=51, null=True, verbose_name='Имя(дательный падеж)'),
        ),
        migrations.AlterField(
            model_name='students',
            name='form_of_education',
            field=models.CharField(choices=[('О', 'Очная'), ('З', 'Заочная'), ('ОЗ', 'Очно-заочная')], max_length=20, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name_dp',
            field=models.CharField(max_length=51, null=True, verbose_name='Фамилия(дательный падеж)'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name_dp',
            field=models.CharField(max_length=51, null=True, verbose_name='Отчество(дательный падеж)'),
        ),
        migrations.AlterField(
            model_name='students',
            name='qualification',
            field=models.CharField(max_length=40, null=True, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='students',
            name='seria_and_numder',
            field=models.CharField(max_length=40, null=True, verbose_name='Серия и номер'),
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('м', 'мужской'), ('ж', 'женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='students',
            name='snils',
            field=models.CharField(max_length=14, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='students',
            name='year_education',
            field=models.CharField(max_length=4, null=True, verbose_name='Год выдачи предыдущего документа об образовании'),
        ),
    ]
