# Generated by Django 3.2.6 on 2021-09-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210827_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.directions', verbose_name='Направление'),
        ),
    ]
