# Generated by Django 3.2.6 on 2021-09-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_groups_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='students',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.countries', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='students',
            name='education_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.documents', verbose_name='Документ об образовании'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name_dp',
            field=models.CharField(blank=True, max_length=51, null=True, verbose_name='Имя(дательный падеж)'),
        ),
        migrations.AlterField(
            model_name='students',
            name='form_of_education',
            field=models.CharField(blank=True, choices=[('О', 'Очная'), ('З', 'Заочная'), ('ОЗ', 'Очно-заочная')], max_length=20, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name_dp',
            field=models.CharField(blank=True, max_length=51, null=True, verbose_name='Фамилия(дательный падеж)'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name_dp',
            field=models.CharField(blank=True, max_length=51, null=True, verbose_name='Отчество(дательный падеж)'),
        ),
        migrations.AlterField(
            model_name='students',
            name='qualification',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='students',
            name='seria_and_numder',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Серия и номер'),
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(blank=True, choices=[('м', 'мужской'), ('ж', 'женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='students',
            name='snils',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='students',
            name='year_education',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Год выдачи предыдущего документа об образовании'),
        ),
    ]
