# Generated by Django 3.2.6 on 2021-09-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210915_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(blank=True, choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
