# Generated by Django 3.2.6 on 2021-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_students_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='form_of_education',
            field=models.CharField(blank=True, choices=[('Очная', 'Очная'), ('Заочная', 'Заочная'), ('Очно-заочная', 'Очно-заочная')], max_length=20, null=True, verbose_name='Форма обучения'),
        ),
    ]
